spring:
  profiles:
    active: docker
---
spring:
  profiles: docker
  redis:
    host: 10.0.2.109
    port: 6379
  datasource:
    url: jdbc:mysql://10.0.2.109:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.2.109:8761/eureka/
