spring:
  profiles:
    active: docker
---
spring:
  profiles: docker
  neo4j:
    host: 10.0.2.109
    port: 7474
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.2.109:8761/eureka/
