spring:
  profiles:
    active: docker
---
spring:
  profiles: docker
  data:
    mongodb:
      host: 10.0.2.109
      port: 27017
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
security:
  oauth2:
    resource:
      userInfoUri: http://10.0.2.109:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.0.2.109:8761/eureka/
